services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --save 60 1
    restart: unless-stopped


  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - PYTHONUNBUFFERED=1
      - LMSTUDIO_URL=http://host.docker.internal:1234/api/v1/chat
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./data_extract:/app/data_extract
    restart: unless-stopped

  producer-api:
    build: ./producer
    ports:
      - "3001:3001"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    restart: unless-stopped